package com.dazednconfused.catalauncher.database.mod;

import com.dazednconfused.catalauncher.database.BaseDAO;
import com.dazednconfused.catalauncher.database.DAOException;
import com.dazednconfused.catalauncher.database.H2Database;
import com.dazednconfused.catalauncher.database.mod.entity.ModfileEntity;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Map;
import java.util.Optional;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ModfilesH2DAOImpl extends H2Database implements BaseDAO<ModfileEntity> {

    private static final Logger LOGGER = LoggerFactory.getLogger(ModfilesH2DAOImpl.class);

    private static final String DATABASE_FILE = "mods";
    private static final String MOD_FILES_TABLE_NAME = "modfile";

    @Override
    public String getDatabaseName() {
        return DATABASE_FILE;
    }

    @Override
    public String getTableName() {
        return MOD_FILES_TABLE_NAME;
    }

    /**
     * Initializes the {@link #MOD_FILES_TABLE_NAME} table.
     * */
    @Override
    public Map.Entry<Connection, PreparedStatement> getTableCreationStatement() throws DAOException {
        try {
            String sql = "CREATE TABLE IF NOT EXISTS " + MOD_FILES_TABLE_NAME + " (" +
                "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "path TEXT NOT NULL," +
                "hash TEXT NOT NULL," +
                "created_date DATETIME NOT NULL," +
                "updated_date DATETIME NOT NULL" +
                ")";

            Connection conn = this.getConnection();
            return Map.entry(conn, conn.prepareStatement(sql));
        } catch (SQLException e) {
            LOGGER.error("An error occurred while crafting table creation statement for [{}]", MOD_FILES_TABLE_NAME, e);
            throw new DAOException(e);
        }
    }

    @Override
    public ModfileEntity insert(ModfileEntity entity) throws DAOException {
        LOGGER.debug("Inserting ModfileEntity [{}]...", entity);

        String sql = "INSERT INTO " + MOD_FILES_TABLE_NAME + "" +
            "(path, hash, created_date, updated_date) " +
            "VALUES " +
            "(?, ?, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP())";

        try (Connection conn = this.getConnection(); PreparedStatement pstmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            pstmt.setString(1, entity.getPath());
            pstmt.setString(2, entity.getHash());

            pstmt.executeUpdate();

            return this.getLatestGeneratedId(pstmt).map(this::findById).orElseThrow(DAOException::new).orElseThrow(DAOException::new);
        } catch (SQLException e) {
            LOGGER.error("An error occurred while inserting entity [{}]", entity, e);
            throw new DAOException(e);
        }
    }

    @Override
    public ModfileEntity update(ModfileEntity entity) throws DAOException {
        Optional<ModfileEntity> originalEntity = this.findById(entity.getId());

        if (originalEntity.isEmpty()) {
            throw new DAOException("No entity with id [" + entity.getId() + "] found");
        }

        LOGGER.debug("Updating ModfileEntity from [{}] to [{}]...", originalEntity.get(), entity);

        String sql = "UPDATE " + MOD_FILES_TABLE_NAME + " SET " +
            "path = ?, " +
            "hash = ?, " +
            "updated_date = CURRENT_TIMESTAMP() " +
            "WHERE id = ?";

        try (Connection conn = this.getConnection(); PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setString(1, entity.getPath());
            pstmt.setString(2, entity.getHash());
            pstmt.setLong(3, entity.getId());

            pstmt.executeUpdate();

            return this.findById(entity.getId()).orElseThrow(DAOException::new);
        } catch (SQLException e) {
            LOGGER.error("An error occurred while updating entity [{}]", entity, e);
            throw new DAOException(e);
        }
    }

    @Override
    public ModfileEntity buildFromResultSet(ResultSet rs) throws DAOException {
        LOGGER.trace("Building ModfileEntity from ResultSet [{}]...", rs);

        try {
            return ModfileEntity.builder()
                .id(rs.getLong("id"))
                .path(rs.getString("path"))
                .hash(rs.getString("hash"))
                .createdDate(rs.getTimestamp("created_date"))
                .updatedDate(rs.getTimestamp("updated_date"))
                .build();
        } catch (SQLException e) {
            LOGGER.error("An error occurred while building entity from ResultSet [{}]", rs, e);
            throw new DAOException(e);
        }
    }
}