package com.dazednconfused.catalauncher.database.mod;

import com.dazednconfused.catalauncher.database.BaseDAO;
import com.dazednconfused.catalauncher.database.DAOException;
import com.dazednconfused.catalauncher.database.H2Database;
import com.dazednconfused.catalauncher.database.mod.entity.ModEntity;

import org.h2.api.H2Type;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.*;
import java.util.Optional;

public class ModsH2DAOImpl extends H2Database implements BaseDAO<ModEntity> {

    private static final Logger LOGGER = LoggerFactory.getLogger(ModsH2DAOImpl.class);

    private static final String DATABASE_FILE = "mods";
    private static final String MODS_TABLE_NAME = "mod";

    @Override
    public String getDatabaseName() {
        return DATABASE_FILE;
    }

    /**
     * Initializes the {@link #MODS_TABLE_NAME} table.
     * */
    @Override
    public void initializeTable() throws DAOException {
        LOGGER.info("Initializing table [{}]...", MODS_TABLE_NAME);

        String sql = "CREATE TABLE IF NOT EXISTS " + MODS_TABLE_NAME + " (" +
            "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
            "name VARCHAR(255) NOT NULL," +
            "modinfo JSON NOT NULL," +
            "created_date DATETIME NOT NULL," +
            "updated_date DATETIME NOT NULL" +
            ")";

        try (Connection conn = this.getConnection(); Statement stmt = conn.createStatement()) {
            stmt.execute(sql);
            LOGGER.debug("[{}] table initialized successfully", MODS_TABLE_NAME);
        } catch (SQLException e) {
            LOGGER.error("An error occurred while creating table [{}]", MODS_TABLE_NAME, e);
            throw new DAOException(e);
        }

        LOGGER.info("Table initialization completed");
    }

    @Override
    public ModEntity insert(ModEntity entity) throws DAOException {
        LOGGER.debug("Inserting ModEntity [{}]...", entity);

        String sql = "INSERT INTO " + MODS_TABLE_NAME + "" +
            "(name, modinfo, created_date, updated_date) " +
            "VALUES " +
            "(?, ?, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP())";

        try (Connection conn = this.getConnection(); PreparedStatement pstmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            pstmt.setString(1, entity.getName());
            pstmt.setObject(2, entity.getModinfo(), H2Type.JSON);

            pstmt.executeUpdate();

            return this.getLatestGeneratedId(pstmt).map(this::findById).orElseThrow(DAOException::new).orElseThrow(DAOException::new);
        } catch (SQLException e) {
            LOGGER.error("An error occurred while inserting entity [{}]", entity, e);
            throw new DAOException(e);
        }
    }

    @Override
    public ModEntity update(ModEntity entity) throws DAOException {
        Optional<ModEntity> originalEntity = this.findById(entity.getId());

        if (originalEntity.isEmpty()) {
            throw new DAOException("No entity with id [" + entity.getId() + "] found");
        }

        LOGGER.debug("Updating ModEntity from [{}] to [{}]...", originalEntity.get(), entity);

        String sql = "UPDATE " + MODS_TABLE_NAME + " SET " +
            "name = ?, " +
            "modinfo = ?, " +
            "updated_date = CURRENT_TIMESTAMP() " +
            "WHERE id = ?";

        try (Connection conn = this.getConnection(); PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setString(1, entity.getName());
            pstmt.setObject(2, entity.getModinfo(), H2Type.JSON);
            pstmt.setLong(3, entity.getId());

            pstmt.executeUpdate();

            return this.findById(entity.getId()).orElseThrow(DAOException::new);
        } catch (SQLException e) {
            LOGGER.error("An error occurred while updating entity [{}]", entity, e);
            throw new DAOException(e);
        }
    }

    @Override
    public void delete(ModEntity entity) throws DAOException {
        Optional<ModEntity> originalEntity = this.findById(entity.getId());

        if (originalEntity.isEmpty()) {
            throw new DAOException("No entity with id [" + entity.getId() + "] found");
        }

        LOGGER.debug("Deleting ModEntity [{}]...", originalEntity.get());

        String sql = "DELETE FROM " + MODS_TABLE_NAME + " WHERE id = ? ";

        try (Connection conn = this.getConnection(); PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setLong(1, entity.getId());

            pstmt.executeUpdate();
        } catch (SQLException e) {
            LOGGER.error("An error occurred while deleting entity [{}]", entity, e);
            throw new DAOException(e);
        }
    }

    @Override
    public Optional<ModEntity> findById(long id) throws DAOException {
        LOGGER.debug("Finding ModEntity with ID [{}]...", id);

        String sql = "SELECT * FROM " + MODS_TABLE_NAME + " WHERE id = ?";
        try (Connection conn = this.getConnection(); PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setLong(1, id);
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) {
                return Optional.of(this.buildFromResultSet(rs));
            }
        } catch (SQLException e) {
            LOGGER.error("An error occurred while retrieving entity with ID [{}]", id, e);
            throw new DAOException(e);
        }

        return Optional.empty();
    }

    @Override
    public ModEntity buildFromResultSet(ResultSet rs) throws DAOException {
        LOGGER.trace("Building ModEntity from ResultSet [{}]...", rs);

        try {
            return ModEntity.builder()
                .id(rs.getLong("id"))
                .name(rs.getString("name"))
                .modinfo(rs.getString("modinfo"))
                .createdDate(rs.getTimestamp("created_date"))
                .updatedDate(rs.getTimestamp("updated_date"))
                .build();
        } catch (SQLException e) {
            LOGGER.error("An error occurred while building entity from ResultSet [{}]", rs, e);
            throw new DAOException(e);
        }
    }
}