name: Run Commitlint on PR Title

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🔖Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 📝Validate PR title with commitlint
        uses: kevintyj/prlint@v2
        # Optional (with default values)
        with:
          download-dependencies: ignore
          body: false
          timeout: 20000